---

- name: "create users and set password"
  block:
    - name: "create users"
      user:
        name: "{{ item.name }}"
        shell: "{{ item.shell }}"
        group: " {{ item.group }}"
      loop: "{{ users }}"
      
    - name: "change password for users"
      user:
        name: "{{ item.key }}"
        password: "{{ item.value }}"
        update_password: always
      with_dict: "{{ user_passwd }}"
      when: update_password == true
  tags: add_user