---

- name: create local user.
  user:
    name: {{ item.username }}
    password: {{ item.password }}
    state: present
    shell: /bin/bash
  become: yes
  become_method: su
  become_user: root
  with_items: "{{ users }}"