---
### selinux module requires libselinux-python (need to install via yum.)

- name: install libselinux-python
  yum:
      name: libselinux-python
      state: latest

- name: check SELinux state.
  shell: /usr/sbin/getenforce
  register: result

- name: disable SELinux
  selinux:
      state: disabled
  when: result.stdout != "Disabled"
