# main playbook
# このplaybookでは処理は行わずに、インクルードのみを担当する.
# 各種設定処理はoperations配下のyamlに委譲.
- hosts: all
  become: yes
  become_method: su
  tasks:
      - name: initialize Ansible
        tags: allexec
        debug: msg="Start Ansible."

# 各種設定ファイルをインクルード.
#
# OS環境の設定.
# ===============================================================
# FSCK設定の確認
- include: ./operations/fsck.yml
# システムロケールの確認.
- include: ./operations/systemlocale.yml
# アカウント作成、パスワード変更.
- include: ./operations/useradd.yml
# sudo 設定.
- include: ./operations/visudo.yml
# NTP設定.
- include: ./operations/ntp.yml
# DNS設定.
- include: ./operations/dns.yml
# Static Route 設定.
# サービス自動起動の有効・無効
- include: ./operations/chkconfig.yml
# SSH RootLogin 無効化
- include: ./operations/sshd_config.yml
# SFTPサーバのログ出力設定.
- include: ./operations/sftp.yml
# syslog出力設定.
- include: ./operations/rsyslog.yml
# SELinux 無効
#- include: ./operations/selinux.yml
# APIPAの停止
- include: ./operations/apipa.yml
# postfixの設定.
- include: ./operations/postfix.yml
# iptablesの設定.
- include: ./operations/iptables.yml
# ログインチェック処理の設定.
- include: ./operations/put_sshchk.yml
# TCPパラメータの確認.
- include: ./operations/tcp_param.yml
# 仮想コンソール数の変更.
- include: ./operations/active_console.yml

# 最終処理
- include: ./operations/finished.yml
