isreplace_phpconf: True
is_patch: False
with_apache: True
enable_zendgl: True
php_configure: |
  ./configure \
  --with-libdir=lib64 \
  --with-config-file-path=/etc \
  --with-config-file-scan-dir=/etc/php.d \
  --disable-debug \
  --with-pic \
  --disable-rpath \
  --without-pear \
  --with-bz2 \
  --with-exec-dir=/usr/bin \
  --with-freetype-dir=/usr \
  --with-png-dir=/usr \
  --with-xpm-dir=/usr \
  --enable-gd-native-ttf \
  --without-gdbm \
  --with-gettext \
  --with-gmp \
  --with-iconv \
  --with-jpeg-dir=/usr \
  --with-openssl \
  --with-zlib \
  --with-layout=GNU \
  --enable-exif \
  --enable-ftp \
  --enable-magic-quotes \
  --enable-sockets \
  --enable-sysvsem \
  --enable-sysvshm \
  --enable-sysvmsg \
  --with-kerberos \
  --enable-ucd-snmp-hack \
  --enable-shmop \
  --enable-calendar \
  --without-sqlite \
  --with-libxml-dir=/usr \
  --enable-xml \
  --with-mhash \
  --enable-pcntl \
  --enable-mbstring=shared \
  --enable-mbregex \
  --with-gd=shared \
  --enable-bcmath=shared \
  --enable-dba=shared \
  --with-xmlrpc=shared \
  --with-ldap=shared \
  --with-ldap-sasl \
  --with-mysql=shared,mysqlnd \
  --with-mysqli=shared,mysqlnd \
  --enable-dom=shared \
  --with-pgsql=shared \
  --enable-wddx=shared \
  --with-snmp=shared,/usr \
  --enable-soap=shared \
  --with-xsl=shared,/usr \
  --enable-xmlreader=shared \
  --enable-xmlwriter=shared \
  --with-curl=shared,/usr \
  --enable-pdo=shared \
  --with-pdo-odbc=shared,unixODBC,/usr \
  --with-pdo-mysql=shared,mysqlnd \
  --with-pdo-pgsql=shared,/usr \
  --with-pdo-sqlite=shared,/usr \
  --with-sqlite3=shared,/usr \
  --enable-json=shared \
  --enable-zip=shared \
  --without-readline \
  --with-libedit \
  --with-pspell=shared \
  --enable-phar=shared \
  --with-tidy=shared,/usr \
  --enable-sysvmsg=shared \
  --enable-sysvshm=shared \
  --enable-sysvsem=shared \
  --enable-posix=shared \
  --with-unixODBC=shared,/usr \
  --enable-fileinfo=shared \
  --enable-intl=shared \
  --with-mcrypt=shared,/usr \
  --with-icu-dir=/usr \
  --with-enchant=shared,/usr \
  --with-recode=shared,/usr 
php_packages:
  rhel:
    - "gcc"
    - "gcc-c++"
    - "make"
    - "autoconf"
    - "libtool"
    - "bison"
# zlib extension
    - "zlib"
    - "zlib-devel"
# GD extension
    - "libpng"
    - "libpng-devel"
    - "libjpeg"
    - "libjpeg-devel"
    - "libXpm"
    - "libXpm-devel"
# gettext extension
    - "gettext"
    - "gettext-devel"
# GMP extension
    - "gmp"
    - "gmp-devel"
# OpenSSL extension
    - "openssl-devel"
# SNMP extension
    - "net-snmp"
    - "net-snmp-devel"
# Mhash extension
    - "mhash"
    - "mhash-devel"
# LDAP extension
    - "openldap"
    - "openldap-devel"
    - "expat"
# CURL extension
    - "libcurl"
    - "libcurl-devel"
# mcrypt extension
    - "libmcrypt"
    - "libmcrypt-devel"
# ODBC extension with unixODBC
    - "unixODBC"
    - "unixODBC-devel"
# Readline extension
    - "libedit"
    - "libedit-devel"
# Intl extension
    - "libicu"
    - "libicu-devel"
# Pspell extension
    - "aspell"
    - "aspell-devel"
# Tidy extension
    - "libtidy"
    - "libtidy-devel"
# Enchant extension
    - "enchant"
    - "enchant-devel"
# XSL extension
    - "libxslt"
    - "libxslt-devel"
# GD extension with FreeType 2
    - "freetype"
    - "freetype-devel"
# Recode extension
    - "recode"
    - "recode-devel"
# PostgreSQL extension
    - "postgresql-devel"
# libxml core extension
    - "libxml2-devel"
# bz2 extension
    - "bzip2"
    - "bzip2-devel"
# sqlite3 extension
    - "sqlite"
    - "sqlite-devel"
  debian:
    - "gcc"
    - "gcc-c++"
    - "make"
    - "autoconf"
    - "libtool"
    - "bison"
    - "zlib1g"
    - "zlib1g-dev"
    - "libxml2"
    - "libxml2-dev"
php_rm_packages:
  rhel:
    - "gcc"
    - "gcc-c++"
    - "make"
    - "autoconf"
    - "zlib-devel"
    - "libpng-devel"
    - "libjpeg-devel"
    - "libXpm-devel"
    - "gettext-devel"
    - "mhash-devel"
    - "openldap-devel"
    - "gmp-devel"
    - "openssl-devel"
    - "net-snmp-devel"
    - "libcurl-devel"
    - "libmcrypt-devel"
    - "unixODBC-devel"
    - "libedit-devel"
    - "libicu-devel"
    - "aspell-devel"
    - "libtidy-devel"
    - "enchant-devel"
    - "libxslt-devel"
    - "freetype-devel"
    - "recode-devel"
    - "postgresql-devel"
    - "libxml2-devel"
    - "bzip2-devel"
    - "sqlite-devel"