isdeploy_fromgit: False
isdeploy_vhost_static: True
git:
  repo: ""
  dest: ""
  version: ""
conf:
  user: "daemon"
  group: "daemon"
  listen_port: 80
  document_root: "/usr/local/apache2/htdocs"
  custom_log: '"logs/access_log" common'
  error_log: '"logs/error_log"'
  name_virtualhost: "*:80"
vhosts:
  - server_name: "guildem.arad.jp"
    document_root: "/d_fighter/guildem.arad.jp"
    error_log: "/d_fighter/logs/httpd/error_guildem.log"
    custom_log: "/d_fighter/logs/httpd/access_guildem.log combined"
    directories:
      - path: "/d_fighter/guildem.arad.jp"
        directives:
            Options: "FollowSymLinks ExecCGI IncludesNoExec"
  - server_name: "guildemup.arad.jp"
    document_root: "/d_fighter/guildemup.arad.jp"
    error_log: "/d_fighter/logs/httpd/error_guildemup.log"
    custom_log: "/d_fighter/logs/httpd/access_guildemup.log combined"
    directories:
      - path: "/d_fighter/guildemup.arad.jp"
        directives:
            Options: "FollowSymLinks ExecCGI IncludesNoExec"
            AllowOverride: "all"
            Order: "deny,allow"
other_resources:
  - "/d_fighter/core"
  - "/d_fighter/test_html"