# target Section.
- hosts: all
  become: yes
  become_method: su
# variable Section.
  vars_files:
      - ../vars/services/onlist.yml
      - ../vars/services/offlist.yml
# tasks Section.
  tasks:
#      - name: include var_file onlist
#        include_vars:
#            file: ../vars/services/onlist.yml
#            name: onlist
#      - name: include var_file offlist
#        include_vars:
#            file: ../vars/services/offlist.yml
#            name: offlist
      - name: check variable
        debug:
            msg: "{{ offlist }}"

      - name: enable services.
        service:
            name: "{{ item }}"
            enabled: yes
        with_items: "{{ onlist }}"

      - name: disable services.
        service:
            name: "{{ item }}"
            enabled: no
        with_items: "{{ offlist }}"
