# target Section.
- hosts: all
  become: yes
  become_method: su
# variable Section.
  vars_files:
      - ../vars/dns_servers/normal.yml
# tasks Section.
  tasks:
      - name: Copy a new "resolv.conf" file into place
        template:
            src: ../sendfiles/dns/resolve.conf.j2
            dest: /etc/resolv.conf
            owner: root
            group: root
            mode: 0644
          
      # check
      - name: check dns configuration
        shell: nslookup nexon.com
        register: result
        failed_when: result.rc != 0
        ignore_errors: yes
