### ログインチェックスクリプト(perl)の配置.
# target Section.
- hosts: all
  become: yes
  become_method: su
# variable Section.
  vars_files:
      - ../vars/arad_address.yml
# tasks Section.
  tasks:
      - name: check SMTP module existed.
        shell: find / -name 'SMTP.pm'
        register: result
        
      - name: put a login check script to remote host.
        template:
            src: ../sendfiles/sshchk/sshchk.pl.j2
            dest: /etc/profile.d/loginchk_with_root_detect.pl
            owner: root
            group: root
            mode: 0644
        when: result.rc == 0
        
      - name: configuration profile
        lineinfile:
            path: /etc/profile
            line: 'perl /etc/profile.d/loginchk_with_root_detect.pl'