# target Section
- hosts: all
  become: yes
  become_method: su
# variable Section
  vars_files:
      - ../vars/server_list.yml
# tasks Section.
  tasks:
      - name: edit /etc/rsyslog.conf for splunk
        lineinfile:
            path: /etc/rsyslog.conf
            line: '*.* @{{ splunk }}:10530'

- hosts: all
  become: yes
  become_method: su
  vars_files:
      - ../vars/server_list.yml
  vars:
      val1: { reg: '^\*\.info;mail', text: '*.info;mail.none;authpriv.none;auth.none;cron.none /var/log/messages' }
      val2: { reg: '^authpriv\.\*', text: 'authpriv.*;auth.*' }
  tasks:       
      - name: edit /etc/rsyslog.conf for sftp
        lineinfile:
            path: /etc/rsyslog.conf
            state: present
            backrefs: yes
            regexp: "{{ item.reg }}"
            line: "{{ item.text }}"
        with_items:
            - "{{ val1 }}"
            - "{{ val2 }}"
            
      - name: restart rsyslog
        service:
            name: rsyslog
            state: restarted
