### selinux module requires libselinux-python (need to install via yum.)
# target Section.
- hosts: all
  become: yes
  become_method: su
  # variable Section.
# tasks Section.
  tasks:
      - name: install libselinux-python
        yum:
            name: libselinux-python
            state: latest

      - name: check SELinux state.
        shell: /usr/sbin/getenforce
        register: result

      - name: disable SELinux
        selinux:
            state: disabled
        when: result.stdout != "Disabled"
