# target Section.
- hosts: all
  become: yes
  become_method: su
# variable Section.
# tasks Section.
  tasks:
      - name: change setting which output logs for sftp
        lineinfile:
            path: /etc/ssh/sshd_config
            state: present
            backrefs: yes
            regexp: '.*sftp'
            line: 'Subsystem sftp /usr/libexec/openssh/sftp-server -l VERBOSE'
          
      - name: restart sshd
        service:
            name: sshd
            state: restarted