# target Section.
- hosts: all
  become: yes
  become_method: su
# variable Section.
# tasks Section.
  tasks:
      - name: Deny root login.
        lineinfile:
            dest: /etc/ssh/sshd_config
            state: present
            backrefs: yes
            regexp: '^PermitRootLogin'
            line: 'PermitRootLogin no'
            
      - name: restart sshd
        service:
            name: sshd
            state: restarted