# target Section.
- hosts: all
  become: yes
  become_method: su
# Tasks Section.
  tasks:
      - name: include vars file.
        include_vars: ../vars/arad_address.yml

      - name: Copy a new "sudoers" file into place, after passing validation with visudo
        template:
            src: ../sendfiles/visudo/sudoers
            dest: /etc/sudoers
            owner: root
            group: root
            mode: 0440
            validate: '/usr/sbin/visudo -cf %s'
