---
- hosts: targets
  become_user: root
  become: yes
  roles:
    - { role: common_al2, when: "ansible_distribution == 'Amazon'" }
    - { role: common_centos7, when: "ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'" }